In [1]:
import requests
from bs4 import BeautifulSoup  
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
api_key = 'o39LN2yUm0OXvxj4cwjj4ektfPDvWDJpf5fRvqNLQNkvitaMNeNDrKZOt1oaGKcM4ihQcGiUca3QXCr4DeA0X_x-P4kiAnT8OIOy2UjZJsRIg7855OK0aKz1AlvSX3Yx'

In [3]:
business_endpoint = 'https://api.yelp.com/v3/businesses/search'

In [4]:
header_category = {'Authorization': 'bearer %s' % api_key}

In [5]:
params_offset = 50

In [15]:
params_category_music = {'location': 'East Nashville', 'limit': 50, 'categories': 'bars', 'offset': params_offset}

In [16]:
response_business_music = requests.get(url = business_endpoint, params = params_category_music, headers = header_category)

In [17]:
response_business_music.json()

{'error': {'code': 'VALIDATION_ERROR',
  'description': '39050 is greater than the maximum of 1000',
  'field': 'offset',
  'instance': 39050}}

In [18]:
def extract_music_info(music):
    categories =  [a['title'] for a in music['categories']]
    ratings = music['rating']
    name = music['name']
    address = music['location']['display_address']
    latitude = music['coordinates']['latitude']
    longitude = music['coordinates']['longitude']
    try:
        price = music['price']
    except:
        price = 'no price'
    zip_code = music['location']['zip_code']
    is_closed = music['is_closed']
    output_dict_music = { 
                   'categories': categories,   
                   'ratings': ratings,
                   'name': name,
                   'display_address': address,
                   'latitude': latitude, 
                   'longitude': longitude, 
                   'price': price, 
                   'zip_code': zip_code,
                   'is_closed': is_closed}

    return output_dict_music

In [26]:
music_list = []
for increment in range(0, 1000, 50) : 
    response_business_music = requests.get(url = business_endpoint, params = params_category_music, headers = header_category)
    for music_data in response_business_music.json()['business']:
        music_dict = extract_music_info(music_data)
        music_list.append(music_dict)
        params_offset += 50

KeyError: 'business'

In [20]:
music_venues_nash = pd.DataFrame(music_list)
music_venues_nash

Empty DataFrame
Columns: []
Index: []

In [14]:
music_venues_nash['display_address'] = music_venues_nash['display_address'].apply(lambda x: x[0] + x[1])
music_venues_nash

,categories,ratings,name,display_address,latitude,longitude,price,zip_code,is_closed
0,"[Bars, Music Venues]",3.0,Music City Bar and Grill,24,36.219441,-86.698046,$$,37214,False
1,"[Dive Bars, Music Venues]",3.0,Big Shotz,11,36.162327,-86.775764,$,37201,False
2,"[Hot Dogs, Sports Bars, Music Venues]",3.0,DawgHouse Saloon,15,36.153147,-86.790335,$$,37203,False
3,[Music Venues],4.0,The High Watt,1,36.152824,-86.780319,$,37203,False
4,"[Music Venues, American (New), Cocktail Bars]",4.5,Jane’s Hideaway,20,36.164521,-86.778329,no price,37201,False
...,...,...,...,...,...,...,...,...,...
775,"[Music Venues, Coffee & Tea]",4.0,Curb Cafe,20,36.132515,-86.795213,$,37212,False
776,[Music Venues],3.0,Vanderbilt Univ Langford Auditorium,1,36.143219,-86.804222,$,37240,False
777,[Music Venues],1.0,Nashville Center Stage,51,36.153250,-86.778990,no price,37203,False
778,"[Music Venues, Juice Bars & Smoothies]",1.0,The Platform,15,36.139003,-86.759543,no price,37210,False
779,[Music Venues],1.0,Time Travelers Cafe,21,36.152020,-86.804970,no price,37203,False

In [153]:
music_venues_nash['categories'] = music_venues_nash['categories'].apply(lambda x: x[0])
music_venues_nash

,categories,ratings,name,display_address,latitude,longitude,price,zip_code,is_closed
0,Music Venues,4.0,The Bluebird Cafe,"4104 Hillsboro PikeNashville, TN 37215",36.102200,-86.817000,$$,37215,False
1,Bars,4.0,The Local,"110 28th Ave NNashville, TN 37203",36.145910,-86.812620,$$,37203,False
2,Music Venues,3.5,BB King's Blues Club,"152 2nd Ave NNashville, TN 37201",36.163349,-86.775960,$$,37201,False
3,Lounges,4.5,Analog at Hutton Hotel,"1808 W End AveNashville, TN 37203",36.152860,-86.797080,$$,37203,False
4,American (New),3.5,Commodore Grille,"2613 W End AveNashville, TN 37203",36.144580,-86.810830,$$,37203,False
...,...,...,...,...,...,...,...,...,...
795,Music Venues,3.0,Vanderbilt Univ Langford Auditorium,"1 Garland AveNashville, TN 37240",36.143219,-86.804222,$,37240,False
796,Music Venues,1.0,Nashville Center Stage,"514 8th Ave SNashville, TN 37203",36.153250,-86.778990,no price,37203,False
797,Music Venues,1.0,The Platform,"1500 2nd Ave SNashville, TN 37210",36.139003,-86.759543,no price,37210,False
798,Music Venues,1.0,Time Travelers Cafe,"212 Louise AveNashville, TN 37203",36.152020,-86.804970,no price,37203,False
799,Recording & Rehearsal Studios,1.0,South By Sea,"1313 Jewel StNashville, TN 37207",36.194960,-86.754050,no price,37207,False

In [154]:
music_venues_nash.to_csv(r'C:\Users\mia\Desktop\nss\projects\capstone\data\nash_venues.csv', index = False)