In [1]:
import pandas as pd

In [35]:
venues = pd.read_csv('./data/excel_indie_venues.csv', usecols = ['name', 'capacity', 'ages', 'genres_extract', 'outdoor_performance_space', 'lgbt_friendly'])
venues

,name,capacity,ages,genres_extract,outdoor_performance_space,lgbt_friendly
0,The Bluebird Cafe\n,100,All,"Acoustic, Americana, Blues, Folk, Singer-Songw...",NaN,NaN
1,The 5 Spot\n\n\n\n\n,180,21+,"Acoustic, Alternative, Americana, Bluegrass, C...",NaN,NaN
2,Mercy Lounge\n\n\n\n\n\n,500,18+,All,NaN,NaN
3,The Local\n,200,21+,All,NaN,NaN
4,The Crying Wolf\n,"50 (back room), 96 (main bar).",21+,All,NaN,NaN
...,...,...,...,...,...,...
100,Drkmttr Collective\n,NaN,All,\nAll Genres,NaN,NaN
101,Kid Rock's Big Ass Honky Tonk,2000 between all 5 floors.,All,Honky Tonk,NaN,NaN
102,The Rhinestone Stage\n,"100 seated, 125 standing.",All,"\nCountry, Honky Tonk, Western",NaN,NaN
103,6th and Peabody\n,"500 inside, 2000 outside.",All,"\nAcoustic, Americana, Bluegrass, Blues, Count...",NaN,NaN
104,Redneck Riviera\n,NaN,All,"\nCountry, Honky Tonk",NaN,NaN

In [37]:
venues['name'] = venues['name'].str.replace('\n', '')
venues

,name,capacity,ages,genres_extract,outdoor_performance_space,lgbt_friendly
0,The Bluebird Cafe,100,All,"Acoustic, Americana, Blues, Folk, Singer-Songw...",NaN,NaN
1,The 5 Spot,180,21+,"Acoustic, Alternative, Americana, Bluegrass, C...",NaN,NaN
2,Mercy Lounge,500,18+,All,NaN,NaN
3,The Local,200,21+,All,NaN,NaN
4,The Crying Wolf,"50 (back room), 96 (main bar).",21+,All,NaN,NaN
...,...,...,...,...,...,...
100,Drkmttr Collective,NaN,All,All Genres,NaN,NaN
101,Kid Rock's Big Ass Honky Tonk,2000 between all 5 floors.,All,Honky Tonk,NaN,NaN
102,The Rhinestone Stage,"100 seated, 125 standing.",All,"Country, Honky Tonk, Western",NaN,NaN
103,6th and Peabody,"500 inside, 2000 outside.",All,"Acoustic, Americana, Bluegrass, Blues, Country...",NaN,NaN
104,Redneck Riviera,NaN,All,"Country, Honky Tonk",NaN,NaN

In [38]:
venues['genres_extract'] = venues['genres_extract'].str.replace('\n', '')
venues

,name,capacity,ages,genres_extract,outdoor_performance_space,lgbt_friendly
0,The Bluebird Cafe,100,All,"Acoustic, Americana, Blues, Folk, Singer-Songw...",NaN,NaN
1,The 5 Spot,180,21+,"Acoustic, Alternative, Americana, Bluegrass, C...",NaN,NaN
2,Mercy Lounge,500,18+,All,NaN,NaN
3,The Local,200,21+,All,NaN,NaN
4,The Crying Wolf,"50 (back room), 96 (main bar).",21+,All,NaN,NaN
...,...,...,...,...,...,...
100,Drkmttr Collective,NaN,All,All Genres,NaN,NaN
101,Kid Rock's Big Ass Honky Tonk,2000 between all 5 floors.,All,Honky Tonk,NaN,NaN
102,The Rhinestone Stage,"100 seated, 125 standing.",All,"Country, Honky Tonk, Western",NaN,NaN
103,6th and Peabody,"500 inside, 2000 outside.",All,"Acoustic, Americana, Bluegrass, Blues, Country...",NaN,NaN
104,Redneck Riviera,NaN,All,"Country, Honky Tonk",NaN,NaN

In [39]:
venues.to_csv(r'C:\Users\mia\Desktop\nss\projects\capstone\data\indie_venues.csv', index = False)